---
name: CI

on:
  push:
    branches-ignore:
      - master
      - mainline
      - rb/*

env:
  IMAGE_NAME: localhost:5000/fholzer/nginx-brotli
  TEST_IMAGE_NAME: nginx-brotli-test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      registry:
        # Docker Hub image
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          driver-opts: network=host

      - name: Build amd64 image
        uses: docker/build-push-action@v2.9.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: src/
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}

      - name: List locally loaded images
        run: |
          docker images

      - name: Build test image
        uses: docker/build-push-action@v2.9.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: test/
          platforms: linux/amd64
          tags: ${{ env.TEST_IMAGE_NAME }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: |
          docker run --rm ${{ env.TEST_IMAGE_NAME }} /tests.sh
